### ISSUE TITLE
wheels for Windows

### ISSUE THREAD

**Issue by rgbpcb** [pyocd/libusb-package#10]
`README.md` says:

> All releases include wheels for Linux, macOS, and Windows for multiple architectures.

Where exactly do I find these "wheels" for Windows, and how exactly do I use them to install `libusb-package`?

It would be nice if `README.md` made this clear.

As a side note, I ran `pip install .` in the `libusb-package-1.0.26.0` directory, but then
```
import os
os.environ['PYUSB_DEBUG'] = 'debug'
import usb.core
usb.core.find()
```
from [here](https://github.com/pyusb/pyusb/blob/master/docs/faq.rst#user-content-how-do-i-fix-no-backend-available-errors) yields
```
2022-09-03 00:00:00,241 ERROR:usb.libloader:'Libusb 1' could not be found
2022-09-03 00:00:00,241 ERROR:usb.backend.libusb1:Error loading libusb 1.0 backend
2022-09-03 00:00:00,242 ERROR:usb.libloader:'OpenUSB library' could not be found
2022-09-03 00:00:00,242 ERROR:usb.backend.openusb:Error loading OpenUSB backend
2022-09-03 00:00:00,244 ERROR:usb.libloader:'Libusb 0' could not be found
2022-09-03 00:00:00,244 ERROR:usb.backend.libusb0:Error loading libusb 0.1 backend
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python310\lib\site-packages\usb\core.py", line 1309, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available
```

**Comment by Tbruno25** [comment]
`libusb_package` replaces `usb.core`.  

Try using `libusb_package.find()` to see if it solves your issue.

**Comment by rgbpcb** [comment]
My issue is that `README.md` mentions some "wheels for Linux, macOS, and Windows", but doesn't explain where exactly to find these "wheels" (for example for Windows) and how to use them to install `libusb-package`.

For that reason, I don't know how to install `libusb-package`.

**Comment by rgbpcb** [comment]
> The whl files generated can be found on pypi under `Navigation > Download files`

Please put this info into the readme.
